# docker-compose.test.yml
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  api:
    container_name: api_test
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/test_db
    depends_on:
      - db