# docker-compose.test.yml
services:
  api:
    container_name: api_test
    build: .
    ports:
      - "8000:8000"

    command: ["gunicorn", "federated_learning_clinical_safety_server.wsgi:application", "--bind", "0.0.0.0:8000"]