# Generated by Django 5.2 on 2025-04-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('cross_validation', models.FloatField()),
                ('security', models.FloatField()),
            ],
        ),
    ]
