# Generated by Django 5.2 on 2025-05-07 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_cross_validation_flmodel_generalisability_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('relatability', models.FloatField()),
                ('fl_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local_models', to='api.flmodel')),
            ],
        ),
    ]
