# Generated by Django 5.2 on 2025-05-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_localmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='localmodel',
            name='source',
            field=models.CharField(default='St Elsewhere', max_length=100),
            preserve_default=False,
        ),
    ]
