# Generated by Django 5.2 on 2025-05-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_localmodel_source'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flmodel',
            old_name='security',
            new_name='privacy',
        ),
        migrations.RemoveField(
            model_name='localmodel',
            name='relatability',
        ),
        migrations.RemoveField(
            model_name='localmodel',
            name='source',
        ),
        migrations.AddField(
            model_name='localmodel',
            name='leakage_chance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localmodel',
            name='noise_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='localmodel',
            name='privacy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flmodel',
            name='accuracy',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flmodel',
            name='generalisability',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
