# Generated by Django 5.2 on 2025-05-22 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_security_flmodel_privacy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='localmodel',
            old_name='noise_score',
            new_name='noise',
        ),
    ]
