# Generated by Django 5.2 on 2025-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_noise_score_localmodel_noise'),
    ]

    operations = [
        migrations.AddField(
            model_name='flmodel',
            name='leakage_chance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
