name: Docker-Compose Smoke Test
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: Build & start services
        run: |
          docker compose -f docker-compose.test.yml up --build -d

      - name: Verify "api_test" container is up
        run: |
          # Check for a running container named api_test
          if ! docker ps --filter "name=^api_test$" --filter "status=running" -q >/dev/null; then
            echo "❌ api_test container did not start properly"
            # Dump its logs for debugging
            docker logs api_test || true
            exit 1
          fi
          echo "✅ api_test container is Up"
      

      # (Optional) verify port binding rather than full HTTP test
      - name: Check port 8000 is listening
        run: |
          if ! ss -ltn | grep -q ':8000'; then
            echo "❌ Nothing is listening on port 8000"
            docker compose -f docker-compose.test.yml logs api
            exit 1
          fi
          echo "✅ api is listening on 8000"

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml down --volumes --remove-orphans
