name: Docker-Compose Smoke Test
on: [push, pull_request]

jobs:
  compose-test:
    runs-on: ubuntu-latest  # GitHub-hosted runner :contentReference[oaicite:9]{index=9}

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose  # Ubuntu runner :contentReference[oaicite:10]{index=10}

      - name: Build & start services
        run: docker compose -f docker-compose.test.yml up --build -d    # build and detach :contentReference[oaicite:11]{index=11}

      - name: Verify containers are running
        run: docker compose -f docker-compose.test.yml ps                   # ensure Up :contentReference[oaicite:12]{index=12}

      - name: Wait for API (allow 401)
        run: |
          for i in {1..30}; do
            status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8000/api/models/)
            if [[ "$status" == "200" || "$status" == "401" ]]; then
              echo "✅ API is responding with status $status"
              exit 0
            fi
            echo "⏳ Waiting for API (status $status)…"
            sleep 2
          done
          echo "❌ API did not become ready in time"
          docker compose -f docker-compose.test.yml logs api
          exit 1

      - name: Tear down
        if: always()
        run: docker compose -f docker-compose.test.yml down --volumes --remove-orphans  # cleanup :contentReference[oaicite:13]{index=13}
